1. Create a 3x3 NumPy Array and Interchange Rows and Columns

In [1]:
import numpy as np

# Create a 3x3 array with random integers between 1 and 100
arr = np.random.randint(1, 101, size=(3, 3))
print("Original Array:\n", arr)

# Interchange rows and columns (Transpose)
transposed_arr = np.transpose(arr)
print("Transposed Array:\n", transposed_arr)


Original Array:
 [[ 18  68 100]
 [ 43  96  80]
 [ 23  78  74]]
Transposed Array:
 [[ 18  43  23]
 [ 68  96  78]
 [100  80  74]]


2. Reshape a 1D NumPy Array into 2x5 and then into 5x2 Arrays

In [2]:
# Create a 1D array with 10 elements
arr = np.arange(1, 11)
print("Original 1D Array:\n", arr)

# Reshape into 2x5
reshaped_2x5 = arr.reshape(2, 5)
print("Reshaped to 2x5:\n", reshaped_2x5)

# Reshape into 5x2
reshaped_5x2 = arr.reshape(5, 2)
print("Reshaped to 5x2:\n", reshaped_5x2)


Original 1D Array:
 [ 1  2  3  4  5  6  7  8  9 10]
Reshaped to 2x5:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
Reshaped to 5x2:
 [[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


3. Create a 4x4 NumPy Array with Random Float Values and Add a Border of Zeros

In [3]:
# Create a 4x4 array with random float values
arr = np.random.rand(4, 4)
print("Original 4x4 Array:\n", arr)

# Add a border of zeros
bordered_arr = np.pad(arr, pad_width=1, mode='constant', constant_values=0)
print("Array with Zero Border (6x6):\n", bordered_arr)


Original 4x4 Array:
 [[0.5677443  0.57720099 0.60834421 0.62356725]
 [0.19790742 0.09500086 0.33266081 0.24495793]
 [0.43819631 0.484977   0.2839963  0.51446709]
 [0.98662078 0.58931104 0.0679857  0.8657235 ]]
Array with Zero Border (6x6):
 [[0.         0.         0.         0.         0.         0.        ]
 [0.         0.5677443  0.57720099 0.60834421 0.62356725 0.        ]
 [0.         0.19790742 0.09500086 0.33266081 0.24495793 0.        ]
 [0.         0.43819631 0.484977   0.2839963  0.51446709 0.        ]
 [0.         0.98662078 0.58931104 0.0679857  0.8657235  0.        ]
 [0.         0.         0.         0.         0.         0.        ]]


4. Create an Array of Integers from 10 to 60 with a Step of 5

In [4]:
arr = np.arange(10, 65, 5)
print("Array from 10 to 60 with step 5:\n", arr)


Array from 10 to 60 with step 5:
 [10 15 20 25 30 35 40 45 50 55 60]


5. Apply Different Case Transformations to Strings in a NumPy Array

In [7]:
# Create an array of strings
arr = np.array(['python', 'numpy', 'pandas'])

# Apply transformations
uppercase_arr = np.char.upper(arr)
lowercase_arr = np.char.lower(arr)
titlecase_arr = np.char.title(arr)

print("Uppercase:\n", uppercase_arr)
print("Lowercase:\n", lowercase_arr)
print("Titlecase:\n", titlecase_arr)


Uppercase:
 ['PYTHON' 'NUMPY' 'PANDAS']
Lowercase:
 ['python' 'numpy' 'pandas']
Titlecase:
 ['Python' 'Numpy' 'Pandas']


6. Insert a Space Between Each Character in Every Word of a NumPy Array

In [8]:
# Create an array of words
arr = np.array(['python', 'numpy', 'pandas'])

# Insert a space between each character
spaced_arr = np.char.join(' ', arr)

print("Spaced Words:\n", spaced_arr)


Spaced Words:
 ['p y t h o n' 'n u m p y' 'p a n d a s']


7. Perform Element-Wise Operations on Two 2D Arrays

In [9]:
# Create two 2D arrays
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

# Element-wise addition, subtraction, multiplication, and division
add_result = np.add(arr1, arr2)
sub_result = np.subtract(arr1, arr2)
mul_result = np.multiply(arr1, arr2)
div_result = np.divide(arr1, arr2)

print("Addition:\n", add_result)
print("Subtraction:\n", sub_result)
print("Multiplication:\n", mul_result)
print("Division:\n", div_result)


Addition:
 [[ 6  8]
 [10 12]]
Subtraction:
 [[-4 -4]
 [-4 -4]]
Multiplication:
 [[ 5 12]
 [21 32]]
Division:
 [[0.2        0.33333333]
 [0.42857143 0.5       ]]


8. Create a 5x5 Identity Matrix and Extract Diagonal Elements


In [10]:
# Create a 5x5 identity matrix
identity_matrix = np.eye(5)
print("Identity Matrix:\n", identity_matrix)

# Extract diagonal elements
diagonal_elements = np.diag(identity_matrix)
print("Diagonal Elements:\n", diagonal_elements)


Identity Matrix:
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
Diagonal Elements:
 [1. 1. 1. 1. 1.]


9. Find and Display Prime Numbers in an Array of Random Integers

In [11]:
# Create an array of 100 random integers between 0 and 1000
arr = np.random.randint(0, 1001, size=100)

# Function to check for prime numbers
def is_prime(n):
    if n < 2:
        return False
    for i in range(2, int(np.sqrt(n)) + 1):
        if n % i == 0:
            return False
    return True

# Find prime numbers
prime_numbers = np.array([num for num in arr if is_prime(num)])
print("Prime Numbers:\n", prime_numbers)


Prime Numbers:
 [967 619 353 937 829 701 827  59 823 263 431 571 269]


10. Calculate Weekly Averages of Daily Temperatures for a Month

In [12]:
# Create an array representing daily temperatures for a month (30 days)
daily_temps = np.random.randint(15, 40, size=30)
print("Daily Temperatures:\n", daily_temps)

# Reshape into weeks (4 weeks + extra 2 days)
weekly_temps = np.array_split(daily_temps, 5)

# Calculate weekly averages
weekly_averages = [np.mean(week) for week in weekly_temps]
print("Weekly Averages:\n", weekly_averages)


Daily Temperatures:
 [36 18 15 31 39 22 36 31 37 18 29 30 23 35 25 23 33 18 26 32 38 32 31 30
 22 19 21 27 29 29]
Weekly Averages:
 [26.833333333333332, 30.166666666666668, 26.166666666666668, 31.5, 24.5]
